spring:
  data:
    cassandra:
      keyspace-name: main
      username: HCiHTCOztynPMMZuJsiRTIwD
      password: Q57.-J..cv9f4.cki_n.21AIl7BvDlM4DlyZGXxOpXT_FGZ29Z6teYYDS2c0WA67b.4uFuAa-4qpp2r06mleozBHX+t6CCaIMt,jdJw7mXimRS,ZwGdp3fJDlLBPzUvB
      schema-action: CREATE_IF_NOT_EXISTS
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
  devtools:
      livereload:
          enabled: false
          port: 35730
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.a5a7e1fb371f3522 #From setting up app in github
            client-secret: 2cce8fc8b1a3454b39c883f0adf4d8cff4717b94 #From setting up app in github 
  application:
    name: magnificentmedia                     

datastax:
  astra:
    secure-connect-bundle: secure-connect.zip

astra.db:
    id: 34127a77-5661-4e8a-913d-b5cc9a90bfda-1
    region: us-east1
    keyspace: main
    application.token: AstraCS:HCiHTCOztynPMMZuJsiRTIwD:55942f80d1e98b13ccb42a0ac341097f020e7ac67408ec7a6c49f8204e1a0b85

spring.main.allow-circular-references: true